export { Layout, Back } from "./layout";
export { default as Home } from "./home";
export { default as Users } from "./users";
export { default as Search } from "./search";
// export { default as Help } from "./help";
export { default as About } from "./about";
export { default as Error } from "./error";
export { default as ErrorFallBack } from "./errorFallback";
export { default as Profile } from "./profile";
export { default as ProfileDisplay } from "./profileDisplay";
export { default as Register } from "./register";
export { default as UpdatePassword } from "./update";
export { Footer } from "./avatar";
